// 通用

// user
export const ACTION_LOGIN = 'LOGIN';
export const ACTION_LOGIN_FULFILLED = 'LOGIN_FULFILLED';
export const ACTION_MODIFY_PASSWORD = 'MODIFY_PASSWORD';
export const ACTION_MODIFY_PASSWORD_FULFILLED = 'ACTION_MODIFY_PASSWORD_FULFILLED';
export const ACTION_MODIFY_PASSWORD_UID = 'MODIFY_PASSWORD_UID';
export const ACTION_MODIFY_PASSWORD_UID_FULFILLED = 'ACTION_MODIFY_PASSWORD_UID_FULFILLED';
export const ACTION_GET_USER_INFO = 'GET_USER_INFO';
export const ACTION_GET_USER_INFO_FULFILLED = 'ACTION_GET_USER_INFO_FULFILLED';
export const ACTION_UPDATE_USER_INFO = 'ACTION_UPDATE_USER_INFO';
export const ACTION_UPDATE_USER_INFO_FULFILLED = 'ACTION_UPDATE_USER_INFO_FULFILLED';
export const ACTION_CREATE_USER = 'ACTION_CREATE_USER';
export const ACTION_CREATE_USER_FULFILLED = 'ACTION_CREATE_USER_FULFILLED';
export const ACTION_RESET_PASSWORD = 'ACTION_RESET_PASSWORD';
export const ACTION_RESET_PASSWORD_FULFILLED = 'ACTION_RESET_PASSWORD_FULFILLED';
// userList
export const ACTION_FETCH_USER_LIST = 'ACTION_FETCH_USER_LIST';
export const ACTION_FETCH_USER_LIST_FULFILLED = 'ACTION_FETCH_USER_LIST_FULFILLED';
export const ACTION_PAGE_LOADING = 'ACTION_PAGE_LOADING';
export const ACTION_CHANGE_SEARCH_INPUT = 'ACTION_CHANGE_SEARCH_INPUT';
export const ACTION_CHANGE_SEARCH_INPUT_VISIBLE = 'ACTION_CHANGE_SEARCH_INPUT_VISIBLE';
export const ACTION_DELETE_USER = 'ACTION_DELETE_USER';
export const ACTION_DELETE_USER_FULFILLED = 'ACTION_DELETE_USER_FULFILLED';
export const ACTION_UPDATE_USER_DIALOG_VISIBLE = 'ACTION_UPDATE_USER_DIALOG_VISIBLE';
export const ACTION_UPDATING_USER_INFO = 'ACTION_UPDATING_USER_INFO'; // 用户列表中更新
export const ACTION_UPDATE_USER_INFO_LOADING = 'ACTION_UPDATE_USER_INFO_LOADING';
export const ACTION_UPDATE_USER_NICKNAME = 'ACTION_UPDATE_USER_NICKNAME';
export const ACTION_ADMIN_UPDATE_USER_INFO = 'ACTION_ADMIN_UPDATE_USER_INFO';
export const ACTION_ADMIN_UPDATE_USER_INFO_FULFILLED = 'ACTION_ADMIN_UPDATE_USER_INFO_FULFILLED';
// home
export const ACTION_COLLAPSE_MENU = "COLLAPSE_MENU";
export const ACTION_FILL_MENU_VALUES = "FILL_MENU_VALUES";
export const ACTION_FILL_PAGE_CONTENT = 'FILL_PAGE_CONTENT';
// project manager
export const ACTION_SHOW_LOGO_PREVIEW = 'ACTION_SHOW_LOGO_PREVIEW';
export const ACTION_UPLOAD_LOGO = 'ACTION_UPLOAD_LOGO';
export const ACTION_GET_LOGO_FILE = 'ACTION_GET_LOGO_FILE';
export const ACTION_CREATE_PROJECT = 'ACTION_CREATE_PROJECT';
export const ACTION_CREATE_PROJECT_FULFILLED = 'ACTION_CREATE_PROJECT_FULFILLED';
export const ACTION_UPDATE_PROJECT_LOADING = 'ACTION_UPDATE_PROJECT_LOADING';
export const ACTION_UPDATE_PROJECT_DES = 'ACTION_UPDATE_PROJECT_DES';
export const ACTION_UPDATE_PROJECT_INFO = 'ACTION_UPDATE_PROJECT_INFO';
export const ACTION_UPDATE_PROJECT_INFO_FULFILLED = 'ACTION_UPDATE_PROJECT_INFO_FULFILLED';
export const ACTION_DELETE_PROJECT = 'ACTION_DELETE_PROJECT';
export const ACTION_DELETE_PROJECT_FULFILLED = 'ACTION_DELETE_PROJECT_FULFILLED';
export const ACTION_DELETE_PROJECT_LOADING = 'ACTION_DELETE_PROJECT_LOADING';
// project list
export const ACTION_PROJECT_PAGE_LOADING = 'ACTION_PROJECT_PAGE_LOADING';
export const ACTION_FETCH_PROJECT_LIST = 'ACTION_FETCH_PROJECT_LIST';
export const ACTION_FETCH_PROJECT_LIST_FULFILLED = 'ACTION_FETCH_PROJECT_LIST_FULFILLED';
export const ACTION_FETCH_JOINED_PROJECT_LIST = 'ACTION_FETCH_JOINED_PROJECT_LIST';
export const ACTION_FETCH_JOINED_PROJECT_LIST_FULFILLED = 'ACTION_FETCH_JOINED_PROJECT_LIST_FULFILLED';
export const ACTION_UPDATE_PROJECT_DIALOG_VISIBLE = 'ACTION_UPDATE_PROJECT_DIALOG_VISIBLE';
export const ACTION_DELETE_PROJECT_DIALOG_VISIBLE = 'ACTION_DELETE_PROJECT_DIALOG_VISIBLE';
export const ACTION_PROJECT_USER_MANAGER_DIALOG_VISIBLE = 'ACTION_PROJECT_USER_MANAGER_DIALOG_VISIBLE';
export const ACTION_PROJECT_QUIT_PROJECT_DIALOG_VISIBLE = 'ACTION_PROJECT_QUIT_PROJECT_DIALOG_VISIBLE';
export const ACTION_UPDATING_PROJECT_INFO = 'ACTION_UPDATING_PROJECT_INFO';
export const ACTION_CHANGE_SEARCH_PROJECT_INPUT = 'ACTION_CHANGE_SEARCH_PROJECT_INPUT';
export const ACTION_CHANGE_SEARCH_PROJECT_INPUT_VISIBLE = 'ACTION_CHANGE_SEARCH_PROJECT_INPUT_VISIBLE';
// project user manager
export const ACTION_INIT_PROJECT_MEMBER_DIALOG = 'ACTION_INIT_PROJECT_MEMBER_DIALOG';
export const ACTION_PROJECT_USER_MANAGER_CHANGE_ACCOUNT = 'ACTION_PROJECT_USER_MANAGER_CHANGE_ACCOUNT';
export const ACTION_PROJECT_USER_ADD_ACCOUNT = 'ACTION_PROJECT_USER_ADD_ACCOUNT';
export const ACTION_PROJECT_USER_ADD_ACCOUNT_FULFILLED = 'ACTION_PROJECT_USER_ADD_ACCOUNT_FULFILLED';
export const ACTION_FETCH_PROJECT_MEMBER_LIST = 'ACTION_FETCH_PROJECT_MEMBER_LIST';
export const ACTION_FETCH_PROJECT_MEMBER_LIST_FULFILLED = 'ACTION_FETCH_PROJECT_MEMBER_LIST_FULFILLED';
export const ACTION_DELETE_PROJECT_MEMBER = 'ACTION_DELETE_PROJECT_MEMBER';
export const ACTION_DELETE_PROJECT_MEMBER_FULFILLED = 'ACTION_DELETE_PROJECT_MEMBER_FULFILLED';
export const ACTION_SELECT_PROJECT_MEMBER = 'ACTION_SELECT_PROJECT_MEMBER';
export const ACTION_QUIT_PROJECT = 'ACTION_QUIT_PROJECT';
export const ACTION_QUIT_PROJECT_FULFILLED = 'ACTION_QUIT_PROJECT_FULFILLED';
// dashboard
export const ACTION_FETCH_DASHBOARD_DATA = "ACTION_FETCH_DASHBOARD_DATA";
export const ACTION_FETCH_DASHBOARD_DATA_FULFILLED = "ACTION_FETCH_DASHBOARD_DATA_FULFILLED";
// archive
export const ACTION_ARCHIVE_SELECT_PROJECT = "ACTION_ARCHIVE_SELECT_PROJECT";
export const ACTION_ARCHIVE_SELECT_PLATFORM = "ACTION_ARCHIVE_SELECT_PLATFORM";
export const ACTION_ARCHIVE_SELECT_ARCHIVE_DES = "ACTION_ARCHIVE_SELECT_ARCHIVE_DES";
export const ACTION_ARCHIVE_FETCH_ALL_PROJECTS = "ACTION_ARCHIVE_FETCH_ALL_PROJECTS";
export const ACTION_ARCHIVE_FETCH_ALL_PROJECTS_FULFILLED = "ACTION_ARCHIVE_FETCH_ALL_PROJECTS_FULFILLED";
export const ACTION_ARCHIVE_FETCH_ARCHIVES = "ACTION_ARCHIVE_FETCH_ARCHIVES";
export const ACTION_ARCHIVE_FETCH_ARCHIVES_FULFILLED = "ACTION_ARCHIVE_FETCH_ARCHIVES_FULFILLED";
export const ACTION_ARCHIVE_DELETE_ARCHIVE = "ACTION_ARCHIVE_DELETE_ARCHIVE";
export const ACTION_ARCHIVE_DELETE_ARCHIVE_FULFILLED = "ACTION_ARCHIVE_DELETE_ARCHIVE_FULFILLED";
export const ACTION_DOWNLOAD_ARCHIVE_DIALOG_VISIBLE = 'ACTION_DOWNLOAD_ARCHIVE_DIALOG_VISIBLE';
export const ACTION_ARCHIVE_SET_DOWNLOAD_INFO = 'ACTION_ARCHIVE_SET_DOWNLOAD_INFO';
export const ACTION_ARCHIVE_BUILD_DOWNLOAD_QR_CODE = 'ACTION_ARCHIVE_BUILD_DOWNLOAD_QR_CODE';
export const ACTION_ARCHIVE_BUILD_DOWNLOAD_QR_CODE_FULFILLED = 'ACTION_ARCHIVE_BUILD_DOWNLOAD_QR_CODE_FULFILLED';
export const ACTION_ARCHIVE_GET_ARCHIVE_FILE = 'ACTION_ARCHIVE_GET_ARCHIVE_FILE';
export const ACTION_ARCHIVE_UPLOAD = 'ACTION_ARCHIVE_UPLOAD';
export const ACTION_ARCHIVE_UPLOAD_FULFILLED = 'ACTION_ARCHIVE_UPLOAD_FULFILLED';