// 通用

// user
export const ACTION_LOGIN = 'LOGIN';
export const ACTION_MODIFY_PASSWORD = 'MODIFY_PASSWORD';
export const ACTION_MODIFY_PASSWORD_UID = 'MODIFY_PASSWORD_UID';
export const ACTION_GET_USER_INFO = 'GET_USER_INFO';
export const ACTION_UPDATE_USER_INFO = 'ACTION_UPDATE_USER_INFO';
export const ACTION_CREATE_USER = 'ACTION_CREATE_USER';
export const ACTION_RESET_PASSWORD = 'ACTION_RESET_PASSWORD';
// userList
export const ACTION_FETCH_USER_LIST = 'ACTION_FETCH_USER_LIST';
export const ACTION_PAGE_LOADING = 'ACTION_PAGE_LOADING';
// home
export const ACTION_COLLAPSE_MENU = "COLLAPSE_MENU";
export const ACTION_FILL_MENU_VALUES = "FILL_MENU_VALUES";
export const ACTION_FILL_PAGE_CONTENT = 'FILL_PAGE_CONTENT';
