// 通用

// user
export const ACTION_LOGIN = 'LOGIN';
export const ACTION_LOGIN_FULFILLED = 'LOGIN_FULFILLED';
export const ACTION_MODIFY_PASSWORD = 'MODIFY_PASSWORD';
export const ACTION_MODIFY_PASSWORD_FULFILLED = 'ACTION_MODIFY_PASSWORD_FULFILLED';
export const ACTION_MODIFY_PASSWORD_UID = 'MODIFY_PASSWORD_UID';
export const ACTION_MODIFY_PASSWORD_UID_FULFILLED = 'ACTION_MODIFY_PASSWORD_UID_FULFILLED';
export const ACTION_GET_USER_INFO = 'GET_USER_INFO';
export const ACTION_GET_USER_INFO_FULFILLED = 'ACTION_GET_USER_INFO_FULFILLED';
export const ACTION_UPDATE_USER_INFO = 'ACTION_UPDATE_USER_INFO';
export const ACTION_UPDATE_USER_INFO_FULFILLED = 'ACTION_UPDATE_USER_INFO_FULFILLED';
export const ACTION_CREATE_USER = 'ACTION_CREATE_USER';
export const ACTION_CREATE_USER_FULFILLED = 'ACTION_CREATE_USER_FULFILLED';
export const ACTION_RESET_PASSWORD = 'ACTION_RESET_PASSWORD';
export const ACTION_RESET_PASSWORD_FULFILLED = 'ACTION_RESET_PASSWORD_FULFILLED';
// userList
export const ACTION_FETCH_USER_LIST = 'ACTION_FETCH_USER_LIST';
export const ACTION_FETCH_USER_LIST_FULFILLED = 'ACTION_FETCH_USER_LIST_FULFILLED';
export const ACTION_PAGE_LOADING = 'ACTION_PAGE_LOADING';
export const ACTION_CHANGE_SEARCH_INPUT = 'ACTION_CHANGE_SEARCH_INPUT';
export const ACTION_CHANGE_SEARCH_INPUT_VISIBLE = 'ACTION_CHANGE_SEARCH_INPUT_VISIBLE';
export const ACTION_DELETE_USER = 'ACTION_DELETE_USER';
export const ACTION_DELETE_USER_FULFILLED = 'ACTION_DELETE_USER_FULFILLED';
// home
export const ACTION_COLLAPSE_MENU = "COLLAPSE_MENU";
export const ACTION_FILL_MENU_VALUES = "FILL_MENU_VALUES";
export const ACTION_FILL_PAGE_CONTENT = 'FILL_PAGE_CONTENT';
// project manager
export const ACTION_SHOW_LOGO_PREVIEW = 'ACTION_SHOW_LOGO_PREVIEW';
export const ACTION_UPLOAD_LOGO = 'ACTION_UPLOAD_LOGO';
export const ACTION_GET_LOGO_FILE = 'ACTION_GET_LOGO_FILE';
export const ACTION_CREATE_PROJECT = 'ACTION_CREATE_PROJECT';
export const ACTION_CREATE_PROJECT_FULFILLED = 'ACTION_CREATE_PROJECT_FULFILLED';
// project list
export const ACTION_PROJECT_PAGE_LOADING = 'ACTION_PROJECT_PAGE_LOADING';
export const ACTION_FETCH_PROJECT_LIST = 'ACTION_FETCH_PROJECT_LIST';
export const ACTION_FETCH_PROJECT_LIST_FULFILLED = 'ACTION_FETCH_PROJECT_LIST_FULFILLED';